# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7e72011d690dcc92bd6761a12f9ae3499779ab79e609fe4e16c6cb2dcf6f37196e3a9fd6406a000d4c035881887798b79dc19841c4c57c1cadf06405935686ee

test:
  secret_key_base: d68d42715d2060a45fd33cf186cbd64968e97bf79331d3a8abd00002fa0f07da5a9c2f34d1938e7b6f772f5c5c3c437e4b157d3bcd46b55fbed3e2d76dbe3a52

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
